### ISSUE TITLE
Traceback (most recent call last):   File ".\mission1.py", line 64, in <module>     import env_lab      # noqa ModuleNotFoundError: No module named 'env_lab'

### ISSUE THREAD

**Issue by miguel-superman** [CiscoDevNet/dne-dna-code#85]
Can someone direct me to where this module is located ..

**Comment by NigarumOvum** [comment]
i got same error... 

Traceback (most recent call last):
  File "cmd_runner.py", line 4, in <module>
    import env_lab
ModuleNotFoundError: No module named 'env_lab'

**Comment by NigarumOvum** [comment]
(netdevops38.2) nigarumovum@kubernetes-master:~/Transferências/labs/dnav3-coe/intro-dnac/04_Cmd_Runner$ python cmd_runner.py 
Traceback (most recent call last):
  File "cmd_runner.py", line 4, in <module>
    import env_lab
ModuleNotFoundError: No module named 'env_lab'
(netdevops38.2) nigarumovum@kubernetes-master:~/Transferências/labs/dnav3-coe/intro-dnac/04_Cmd_Runner$ python -m pip install env_lab
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement env_lab (from versions: none)
ERROR: No matching distribution found for env_lab

**Comment by annegentle** [comment]
Hi, `env_lab` in this case is a local file that contains your credentials, and it's located at the root of the cloned directory: https://github.com/CiscoDevNet/dnav3-code/blob/master/env_lab.py is one example. 

I'm guessing that running a Python script in the /intro-dnac/04_Cmd_Runner folder means Python can't "find a version that satisfies the requirement env_lab." That or the "dnav3-coe" folder does not have this file. Let us know how it goes.

**Comment by annegentle** [comment]
Hi again, did you get this one resolved by using the `env_lab.py` file located in the folder where the Python script runs?

**Comment by annegentle** [comment]
Fixed; closing.
